services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_with_vector
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_server
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@uniandes.edu.co
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json   # <- Línea agregada
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmindata: